name: BuildAndTest
on: [ push ]
jobs:
  build:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Build
        run: For /R %%I in (*.sln) do dotnet build %%I
      - name: Run tests
        run: For /R %%I in (*.sln) do dotnet test %%I