name: BuildAndTest
on: [ push ]
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Build
        run: for dir in */; do cd $dir; for i in *.sln; do dotnet build $i; cd ..; done; done
        shell: bash
      - name: RunTests
        run: for dir in */; do cd $dir; for i in *.sln; do dotnet test $i; cd ..; done; done
        shell: bash