name: BuildAndTest
on: [ push ]
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Build
        run: for %i in (*.sln) do dotnet build %i
      - name: Run tests
        run: for %i in (*.sln) do dotnet test %i
        shell: bash